server {
    # Listen on port 80 (default HTTP port)
    listen 80;

    # Define the server name (can be changed to a domain if needed)
    server_name localhost;

    # Set the root directory where the static files are located
    root /usr/share/nginx/html;

    # Define the default file to serve when accessing the root URL
    index index.html;

    location / {
        # Try to serve the requested file first
        # If not found, fallback to index.html (important for React SPA)
        try_files $uri /index.html;
    }

    # If the requested route exists (/about, /contact), Nginx serves the correct static file.
    # If it doesn’t exist (/random-page), Nginx serves index.html, and React renders <NoPage />.
    error_page 404 /index.html;
}
